common: &common
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: localhost
  port: 5432
  pool: 100
  wait_timeout: 10


# Fairly obvious this one :-) - local machine development
development:
  << : *common
  database: slowen_development

# Used by developer to run unit tests on local machine
test:
  << : *common
  database: slowen_test

# Hopefully this is obvious too :-)
production:
  << : *common
  database: slowen_production
